# NumPy Basics

A comprehensive guide to NumPy, the fundamental package for numerical computing in Python.

## 1. Import NumPy

Import NumPy and verify the installation version.

In [1]:
import numpy as np

# Check NumPy version
print(f"NumPy version: {np.__version__}")
print(f"NumPy location: {np.__file__}")

NumPy version: 2.2.5
NumPy location: c:\Users\sanat\anaconda3\envs\ee4216\lib\site-packages\numpy\__init__.py


## 2. Creating NumPy Arrays

Different methods to create NumPy arrays with various initialization patterns.

In [2]:
# 2.1 Create array from Python list
arr1 = np.array([1, 2, 3, 4, 5])
print("From list:", arr1)
print("Shape:", arr1.shape)
print("Data type:", arr1.dtype)

# 2.2 Create zeros array
arr_zeros = np.zeros((3, 4))
print("\nZeros array (3x4):\n", arr_zeros)

# 2.3 Create ones array
arr_ones = np.ones((2, 3), dtype=int)
print("\nOnes array (2x3):\n", arr_ones)

# 2.4 Create range array
arr_range = np.arange(0, 10, 2)
print("\nRange array (0 to 10, step 2):", arr_range)

# 2.5 Create linearly spaced array
arr_linspace = np.linspace(0, 1, 5)
print("Linspace (0 to 1, 5 points):", arr_linspace)

# 2.6 Create random array
arr_random = np.random.rand(3, 3)
print("\nRandom array (3x3):\n", arr_random)

From list: [1 2 3 4 5]
Shape: (5,)
Data type: int64

Zeros array (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array (2x3):
 [[1 1 1]
 [1 1 1]]

Range array (0 to 10, step 2): [0 2 4 6 8]
Linspace (0 to 1, 5 points): [0.   0.25 0.5  0.75 1.  ]

Random array (3x3):
 [[0.04464173 0.31711705 0.98879738]
 [0.44557011 0.43984749 0.44693798]
 [0.34325923 0.02159319 0.17765023]]


## 3. Array Indexing and Slicing

Accessing and modifying array elements.

In [3]:
# 3.1 1D array indexing
arr_1d = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr_1d)
print("First element:", arr_1d[0])
print("Last element:", arr_1d[-1])

# 3.2 1D array slicing
print("Elements 1 to 3:", arr_1d[1:4])
print("Every 2nd element:", arr_1d[::2])

# 3.3 2D array indexing and slicing
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
print("\n2D Array:\n", arr_2d)
print("Element at [1, 2]:", arr_2d[1, 2])
print("First row:", arr_2d[0, :])
print("First column:", arr_2d[:, 0])

# 3.4 Modify array elements
arr_2d[0, 0] = 99
print("\nAfter modification:\n", arr_2d)

1D Array: [10 20 30 40 50]
First element: 10
Last element: 50
Elements 1 to 3: [20 30 40]
Every 2nd element: [10 30 50]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at [1, 2]: 6
First row: [1 2 3]
First column: [1 4 7]

After modification:
 [[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]


## 4. Array Operations

Element-wise mathematical operations on arrays.

In [4]:
# 4.1 Create test arrays
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# 4.2 Arithmetic operations
print("Array a:", a)
print("Array b:", b)
print("\nAddition:", a + b)
print("Subtraction:", b - a)
print("Multiplication:", a * b)
print("Division:", b / a)
print("Power:", a ** 2)

# 4.3 Operations with scalars
print("\na + 10:", a + 10)
print("a * 2:", a * 2)
print("a / 2:", a / 2)

# 4.4 Comparison operations
print("\na > 2:", a > 2)
print("b == 30:", b == 30)
print("a < 3:", a < 3)

Array a: [1 2 3 4]
Array b: [10 20 30 40]

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Power: [ 1  4  9 16]

a + 10: [11 12 13 14]
a * 2: [2 4 6 8]
a / 2: [0.5 1.  1.5 2. ]

a > 2: [False False  True  True]
b == 30: [False False  True False]
a < 3: [ True  True False False]


## 5. Array Reshaping and Flattening

Changing array dimensions and structure.

In [5]:
# 5.1 Create array
arr = np.arange(12)
print("Original array:", arr)
print("Original shape:", arr.shape)

# 5.2 Reshape to 2D
arr_2d = arr.reshape(3, 4)
print("\nReshaped to (3, 4):\n", arr_2d)
print("New shape:", arr_2d.shape)

# 5.3 Reshape to 3D
arr_3d = arr.reshape(2, 3, 2)
print("\nReshaped to (2, 3, 2):\n", arr_3d)

# 5.4 Flatten (convert back to 1D)
flattened = arr_2d.flatten()
print("\nFlattened:", flattened)
print("Shape:", flattened.shape)

# 5.5 Ravel (similar to flatten but returns view)
raveled = arr_2d.ravel()
print("\nRaveled:", raveled)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Original shape: (12,)

Reshaped to (3, 4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New shape: (3, 4)

Reshaped to (2, 3, 2):
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

Raveled: [ 0  1  2  3  4  5  6  7  8  9 10 11]


## 6. Broadcasting

How NumPy handles operations on arrays of different shapes.

In [6]:
# 6.1 Broadcasting with scalars
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Original array (2x3):\n", arr)
print("\nArray + 10:\n", arr + 10)
print("\nArray * 2:\n", arr * 2)

# 6.2 Broadcasting with different shapes
a = np.array([[1, 2, 3],
              [4, 5, 6]])  # shape (2, 3)
b = np.array([10, 20, 30])  # shape (3,)

print("\n\nArray a (2x3):\n", a)
print("Array b (3,):\n", b)
print("a + b (broadcasting):\n", a + b)

# 6.3 Broadcasting with column vector
c = np.array([[1],
              [2]])  # shape (2, 1)
print("\n\nArray c (2x1):\n", c)
print("a + c (broadcasting):\n", a + c)

Original array (2x3):
 [[1 2 3]
 [4 5 6]]

Array + 10:
 [[11 12 13]
 [14 15 16]]

Array * 2:
 [[ 2  4  6]
 [ 8 10 12]]


Array a (2x3):
 [[1 2 3]
 [4 5 6]]
Array b (3,):
 [10 20 30]
a + b (broadcasting):
 [[11 22 33]
 [14 25 36]]


Array c (2x1):
 [[1]
 [2]]
a + c (broadcasting):
 [[2 3 4]
 [6 7 8]]


## 7. Mathematical Functions

Applying mathematical functions to arrays.

In [7]:
import math

# 7.1 Square root
arr = np.array([1, 4, 9, 16, 25])
print("Array:", arr)
print("Square root:", np.sqrt(arr))

# 7.2 Exponential and logarithm
arr2 = np.array([1, 2, 3, 4])
print("\n\nArray:", arr2)
print("Exponential (e^x):", np.exp(arr2))
print("Natural log:", np.log(arr2))
print("Log base 10:", np.log10(arr2))

# 7.3 Trigonometric functions
angles = np.array([0, math.pi/6, math.pi/4, math.pi/3, math.pi/2])
print("\n\nAngles (radians):", angles)
print("Sine:", np.sin(angles))
print("Cosine:", np.cos(angles))
print("Tangent:", np.tan(angles))

# 7.4 Absolute value
arr3 = np.array([-5, -3, 0, 3, 5])
print("\n\nArray:", arr3)
print("Absolute value:", np.abs(arr3))

Array: [ 1  4  9 16 25]
Square root: [1. 2. 3. 4. 5.]


Array: [1 2 3 4]
Exponential (e^x): [ 2.71828183  7.3890561  20.08553692 54.59815003]
Natural log: [0.         0.69314718 1.09861229 1.38629436]
Log base 10: [0.         0.30103    0.47712125 0.60205999]


Angles (radians): [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


Array: [-5 -3  0  3  5]
Absolute value: [5 3 0 3 5]


## 8. Aggregate Functions

Computing statistics and aggregates on arrays.

In [8]:
# 8.1 Create test array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Array:\n", arr)

# 8.2 Sum and product
print("\n\nSum (all):", np.sum(arr))
print("Sum (rows):", np.sum(arr, axis=1))
print("Sum (columns):", np.sum(arr, axis=0))
print("Product (all):", np.prod(arr))

# 8.3 Mean, median, standard deviation
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("\n\nArray:", arr_1d)
print("Mean:", np.mean(arr_1d))
print("Median:", np.median(arr_1d))
print("Standard deviation:", np.std(arr_1d))
print("Variance:", np.var(arr_1d))

# 8.4 Min, max, and their indices
print("\n\nMinimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Index of min:", np.argmin(arr))
print("Index of max:", np.argmax(arr))

# 8.5 Cumulative sum
print("\n\nCumulative sum:", np.cumsum(arr_1d))

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Sum (all): 45
Sum (rows): [ 6 15 24]
Sum (columns): [12 15 18]
Product (all): 362880


Array: [1 2 3 4 5 6 7 8 9]
Mean: 5.0
Median: 5.0
Standard deviation: 2.581988897471611
Variance: 6.666666666666667


Minimum: 1
Maximum: 9
Index of min: 0
Index of max: 8


Cumulative sum: [ 1  3  6 10 15 21 28 36 45]
